### ISSUE TITLE
V103 UI issue when first loaded

### ISSUE THREAD

**Issue by pixelrust** [hires/Dintree-Virtual#4]
Linux Kubuntu 20.04, GeForce GTX 260 with nvidia-340 drivers

- have a basic patch without any other Dintree module
- import Dintree V103
- what happens: UI issue as in attached screenshot
![v103-UI](https://user-images.githubusercontent.com/4542666/88665327-bbc83a00-d0de-11ea-9bee-9f34123d94a0.png)

- restarting VCV seems to fix the issue
- if a second V103 module is added, its UI is correct
- other Dintree modules seem not to be affected
- (limited testing) mixed results if a Dintree module is already present in the initial patch and one or more V103 modules are added

**Comment by hires** [comment]
Thanks. Several modules including the V103 were not loading the default style properly. Now fixed.
