### ISSUE TITLE
Will not compiled in Windows 10 Pro with MSYS2

### ISSUE THREAD

**Issue by caecos** [hires/Dintree-Virtual#6]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V100-Scanner.cpp.o src/V100-Scanner.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V101-Dual_Envelope.cpp.o src/V101-Dual_Envelope.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V102-Output_Mixer.cpp.o src/V102-Output_Mixer.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V103-Reverb_Delay.cpp.o src/V103-Reverb_Delay.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V104-Four_Vs.cpp.o src/V104-Four_Vs.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V105-Quad_CV_Proc.cpp.o src/V105-Quad_CV_Proc.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/V107-Dual_Slew.cpp.o src/V107-Dual_Slew.cpp
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/plugin.cpp.o src/plugin.cpp
g++ -o plugin.dll build/src/V100-Scanner.cpp.o build/src/V101-Dual_Envelope.cpp.o build/src/V102-Output_Mixer.cpp.o build/src/V103-Reverb_Delay.cpp.o build/src/V104-Four_Vs.cpp.o build/src/V105-Quad_CV_Proc.cpp.o build/src/V107-Dual_Slew.cpp.o build/src/plugin.cpp.o -shared -LC:/msys64/Rack-SDK -lRack
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/src/plugin.cpp.o:plugin.cpp:(.rdata$.refptr.modelV201_Tri_Comparator[.refptr.modelV201_Tri_Comparator]+0x0): undefined reference to `modelV201_Tri_Comparator'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys64/Rack-SDK/compile.mk:59: plugin.dll] Error 1

**Comment by hires** [comment]
Hi, the files for this new module are now added in git.

**Comment by caecos** [comment]
Hi, many thanks…

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Andrew Kilpatrick<mailto:notifications@github.com>
Envoyé le :samedi 28 novembre 2020 14:06
À : hires/Dintree-Virtual<mailto:Dintree-Virtual@noreply.github.com>
Cc : caecos<mailto:caecos@hotmail.ca>; Author<mailto:author@noreply.github.com>
Objet :Re: [hires/Dintree-Virtual] Will not compiled in Windows 10 Pro with MSYS2 (#6)


Hi, the files for this new module are now added in git.
